version: "3.8"

services:

  app:
    build: .
    container_name: esportify_app
    depends_on:
      - db
      - mongodb
    env_file: ".env"
    restart: always
    ports:
      - 80:80
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0.42-debian
    container_name: esportify_bdd
    restart: always
    ports:
      - 3307:3306
    volumes:
      - db_data:/var/lib/mysql

  mongodb:
    image: mongo:8
    restart: always
    container_name: esportify_mongo
    depends_on:
      - db
    volumes:
      - mongo_data:/data/db

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: esportify_pma
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    depends_on:
      - db
    restart: always

volumes:
  db_data:
  mongo_data: