version: "3.8"

services:

  app:
    build: .
    container_name: esportify_app
    ports:
      - 8000:80
    depends_on:
      - db
    restart: always
    volumes:
      - .:/var/www/html

  db:
    image: mysql:8.0.42-debian
    container_name: esportify_bdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MonMotDePasse
      MYSQL_DATABASE: esportify_bdd
      MYSQL_USER: esportify
      MYSQL_PASSWORD: LeMotDePasse
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: esportify_pma
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=MonMotDePasse
    depends_on:
      - db
    restart: always

volumes:
  db_data: